---

env:
  node: true

parser: babel-eslint

rules:
  no-console: off

parserOptions:
  ecmaVersion: 2017
  sourceType: module

extends:
  - 'airbnb-base'
  - plugin:import/errors
  - plugin:import/warnings
